### ISSUE TITLE
finalise search interaction

### ISSUE THREAD

**Issue by gubuntu** [kartoza/feti#48]
Ref spec 3 b v and related. 

- [x] generic search box
- [ ] (optional if single search box works well) Combo boxes and other controls. Use http://pi.mapaproject.org/ and the specs as reference. 

Ref also #68 and #36

**Comment by gubuntu** [comment]
feedback from March:
```
the key thing is that the search facility when i tested it was quite inadequate compared to the brief.  That is what the client wants the app for and it has to be solid and clever.
```

**Comment by gubuntu** [comment]
@cchristelis, @lucernae, please indicate what's not clear about these search requirements. In a nutshell, 'Intuitive, fuzzy free text / keyword searching that returns results a user expects'

**Comment by cchristelis** [comment]
Hi @gubuntu,

@lucernae and I spoke and it seems like elastic search's template indexing might help solve this problem. Please add more details @lucernae, once you have had a look.

**Comment by cchristelis** [comment]
@lucernae, see my comments in the PR.

**Comment by cchristelis** [comment]
Hi @lucernae, 

If I search for "Cape Town Engineering" (without ") I get a result for  "Belcomec Training".
If I search for only "Cape Town" in the staging site I get a lot of results, but " Belcomec Training" is not one of them?

**Comment by lucernae** [comment]
I'm guessing this is because we uses fuzzy search. So, each document will have a certain similarity score. I chop off document which has score less than 1. So, in "Cape Town Engineering", Belcomec Training has score greater than one (perhaps because the term engineering matches). But in "Cape Town" Belcomec is ruled out, because the score is less than 1 (no exact matching term). If we uses query: "Cape Town" engineering (double quotes on Cape Town), Belcomec will be ruled out too because we specify that the term "Cape Town" should exists in the document.

I think the problem here is how do we specify how much fuzziness that we want, because the parameters are unclear.

**Comment by cchristelis** [comment]
Oh, I get it. It is very googly. I like it.

**Comment by cchristelis** [comment]
@gubuntu and @tmcbride1967, 
I would like to make sure that this also meets your expectation.

**Comment by cchristelis** [comment]
This is being re-worked.
