### ISSUE TITLE
implement admin functionality

### ISSUE THREAD

**Issue by gubuntu** [kartoza/feti#81]
input from March:

> This seems to be some way off at the moment?
The key thing is to have one function for courses, where you can search for individual courses (partial name searches must work as well) and access / edit all fields for that course.
Ditto for Provider.

>This is a jumble of different fields which are not navigable (e.g. to edit providers details there are three different options).

>What is required is on point of entry per provider, where all the fields can be edited.  Mandatory fields to be kept to an absolute minimum at this stage while the data is so raw.

This should all be achievable through Django admin configuration.

**Comment by lucernae** [comment]
I don't know if this already satisfied the user, @cchristelis ?

**Comment by gubuntu** [comment]
no, March has never been able to log in. End users (Tim etc. ) have never had credentials to test. At the moment there is a CSRF error ( #109 ) and I can't test.

Plain one-model-per-page Django admin won't cut it. Related (child and parent) tables need to be brought in by configuring Django Admin so that teh user can easily and quickly navigate relationships and search, browse, sort, etc. 

e.g. I find a Provider I want to edit. Staying on that page I might want to add a course, edit an address, move a campus location, etc. 

I think Provider (incorporating Campus and Address) and Course (incorporating all the lookup tables) should be the main entry points for managing data in Django Admin. 

Some example tasks that Timothy specified in an email on 29 June:
 - Add or correct missing data in fields (e.g. phone numbers,
 - Incorrect information
 - Incomplete information (e.g. incomplete addresses)
 - Revised information
 - Inconsistent information (e.g. same provider, different names; inclusion of Pty(Ltd) or T/A (trading as addresses)
 - campus locations

**Comment by lucernae** [comment]
The CSRF part maybe about just misconfiguration.

Another note here perhaps about the address field.
We will include address fields in the campus model admin, perhaps using Django Admin Inline

**Comment by gubuntu** [comment]
The staging deployment is showing some progress here:
 - campuses have courses, addresses and providers inlined
BUT
- Providers and Courses should be the main points of entry to admin, so please remove addresses and even campuses as standalone admin items, they must only be accessible via provider or course inlines
- inlines must be editable from parent view. e.g. If I want to edit a campus address, all I can currently do is choose another one, I can't go directly to edit the existing address.
- you must not be allowed to add another address to a campus. Check for other cases like that which don't make sense. 
- Providers must have campuses inlined. Done cleverly, a provider view could show all campuses, addresses and courses on one page through django admin configuration. 
- Courses must have providers inlined (via campuses) so while editing a course,  you can click through to one of its providers. 
- Courses currently don't have all the look-up tables linked properly according to the database design - the 'National graduate school in education' and 'National certificate vocational' dropdowns come up blank. 
- The main Course and Provider admin list views should have as much out-the-box django admin functionality added so they can be easily searched, filtered and navigated.

**Comment by lucernae** [comment]
@gubuntu 

I encountered several limitation here:

> Providers and Courses should be the main points of entry to admin, so please remove addresses and even campuses as standalone admin items, they must only be accessible via provider or course inlines

I excluded campus. But still provides address entry anyway for the following reasons. I'm still not able to make nested inline for address inside campus inside provider. I tried both grappelli-nested-inlines and django-nested-inlines package, but both are unstable and still have many bugs, like you can't save it, deletes the inline causes errors, etc. It just needs huge effort to debug all that and provide the expected functionality. So, I ditched the idea for now.

> inlines must be editable from parent view. e.g. If I want to edit a campus address, all I can currently do is choose another one, I can't go directly to edit the existing address.

Now we can edit campus inline directly from provider. It is also doable to edit address inline from campus admin, but since you want it excluded, I didn't put the entry (the code is there but I didn't register the admin). To compensate the nested inline (because we want to edit it from the providers), I put a link to address edit page in the campus inline.

Screenshot to discuss (Ignores floating save bar. It show up there because I captured it using chrome extension)
![image](https://cloud.githubusercontent.com/assets/831865/9013537/c447caec-37e6-11e5-9299-e0556cb2e846.png)


> you must not be allowed to add another address to a campus. Check for other cases like that which don't make sense.

Noted. Consider it done.

> Providers must have campuses inlined. Done cleverly, a provider view could show all campuses, addresses and courses on one page through django admin configuration.

Explained in the previous point. Not applicable right now (need huge efforts). But it is doable to have campus inline in the provider admin. But not address inline in campus inline. On another note, it is doable to have address inline in campus admin.

Screenshot to discuss: (Possible implementation of address inline in campus admin)
![image](https://cloud.githubusercontent.com/assets/831865/9013617/4c75d2e2-37e7-11e5-914e-d1dd9a5ee5eb.png)

> Courses must have providers inlined (via campuses) so while editing a course, you can click through to one of its providers.

Providers are listed as clickable link in courses, but not as django inline admin.

Screenshot:
![image](https://cloud.githubusercontent.com/assets/831865/9013998/b6906852-37e9-11e5-960d-76e26e97697e.png)

> Courses currently don't have all the look-up tables linked properly according to the database design - the 'National graduate school in education' and 'National certificate vocational' dropdowns come up blank.

both tables are empty, thus it won't show up. Perhaps something to do with data migration?

> The main Course and Provider admin list views should have as much out-the-box django admin functionality added so they can be easily searched, filtered and navigated.

I provided what occurred to me as needed reasonably. Like filters in change list, etc.
